# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"X\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x14\n\x0crelease_date\x18\x05 \x01(\t\";\n\x08Playlist\x12\x12\n\nid_usuario\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05songs\x18\x03 \x03(\x05\")\n\x13UserPlaylistRequest\x12\x12\n\nid_usuario\x18\x01 \x01(\x05\"$\n\x14PlaylistSongsRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"(\n\x13SongPlaylistRequest\x12\x11\n\tsong_name\x18\x01 \x01(\t2Q\n\x0bUserService\x12\x42\n\x0cListAllUsers\x12\x1f.streaming.PlaylistSongsRequest\x1a\x0f.streaming.User0\x01\x32Q\n\x0bSongService\x12\x42\n\x0cListAllSongs\x12\x1f.streaming.PlaylistSongsRequest\x1a\x0f.streaming.Song0\x01\x32\x61\n\x13UserPlaylistService\x12J\n\x11ListUserPlaylists\x12\x1e.streaming.UserPlaylistRequest\x1a\x13.streaming.Playlist0\x01\x32_\n\x14PlaylistSongsService\x12G\n\x11ListPlaylistSongs\x12\x1f.streaming.PlaylistSongsRequest\x1a\x0f.streaming.Song0\x01\x32\x61\n\x13SongPlaylistService\x12J\n\x11ListSongPlaylists\x12\x1e.streaming.SongPlaylistRequest\x1a\x13.streaming.Playlist0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=30
  _globals['_USER']._serialized_end=62
  _globals['_SONG']._serialized_start=64
  _globals['_SONG']._serialized_end=152
  _globals['_PLAYLIST']._serialized_start=154
  _globals['_PLAYLIST']._serialized_end=213
  _globals['_USERPLAYLISTREQUEST']._serialized_start=215
  _globals['_USERPLAYLISTREQUEST']._serialized_end=256
  _globals['_PLAYLISTSONGSREQUEST']._serialized_start=258
  _globals['_PLAYLISTSONGSREQUEST']._serialized_end=294
  _globals['_SONGPLAYLISTREQUEST']._serialized_start=296
  _globals['_SONGPLAYLISTREQUEST']._serialized_end=336
  _globals['_USERSERVICE']._serialized_start=338
  _globals['_USERSERVICE']._serialized_end=419
  _globals['_SONGSERVICE']._serialized_start=421
  _globals['_SONGSERVICE']._serialized_end=502
  _globals['_USERPLAYLISTSERVICE']._serialized_start=504
  _globals['_USERPLAYLISTSERVICE']._serialized_end=601
  _globals['_PLAYLISTSONGSSERVICE']._serialized_start=603
  _globals['_PLAYLISTSONGSSERVICE']._serialized_end=698
  _globals['_SONGPLAYLISTSERVICE']._serialized_start=700
  _globals['_SONGPLAYLISTSERVICE']._serialized_end=797
# @@protoc_insertion_point(module_scope)
